export const INPUT_CONFIG = {
  activePointers: 5,
  joystickRadius: 56,
  joystickKnobRadius: 22,
  joystickDeadzone: 0.18,
  fireButtonRadius: 42,
  fireHitSlop: 12,
  fireGuardSlop: 14,
  reloadButtonRadius: 28,
  reloadHitSlop: 10,
  reloadGuardSlop: 12,
  edgeMargin: 18,
  controlGap: 14,
  minimumScale: 0.72,
  referenceShortEdge: 360,
} as const;
